### ISSUE TITLE
Tune test generation using fuzzing

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#106]
Some preliminary data on libFuzzer performance, with the "full" file system example (mkdir/rmdir/unlink/create/write/stat/ls/lsr), using 1 hour runs, with stats on coverage gathered every minute.  Error bars are 95% confidence intervals on 5 runs.

![libfuzzer](https://user-images.githubusercontent.com/967816/44744712-9a0d4500-aaba-11e8-8b2d-b48fe67f6e5b.png)

Black is with dictionary and value profile.
Red is with neither.
Green is with just dictionary,
Blue is with just value profile.

There is something fishy with the data, in that coverage gathered after each 60 second run does not monotonically increase, within each run -- in particular, the runs with value profiling occasionally have coverage "spikes" above 1770 PCs, then go back to previous coverage level, which seems wrong.  Still clear from five runs that:

1.  Value profile is more valuable than dictionary, and critical for good coverage.
2.  Dictionary still seems somewhat useful

**Comment by pgoodman** [comment]
Nitpick: coverage should be monotonically non-decreasing.

Is coverage stats something like: the cardinality of a bitset?

So if we're at the high end of one of those spikes, doesn't it mean that, for one of the samples that had such a spike, that the rest of that sample is at least that high?

Random: I wonder if value profiling works with or against the comparison decomposition in things like ASSERT_EQ, which is doing a comversion of data coverage to control flow coverage.


So for one of those runs that gets a peak, doesn't that mean that the level of coverage thereafter in

**Comment by agroce** [comment]
Let me clarify a little

- coverage is whatever libFuzzer's "cov" stat is, so not just PCs, right, it's path
- and yeah I meant monotonically non-decreasing

Also, "no dictionary" is not quite true.  What I did to get this is run libFuzzer, with the same corpus directory, 60 times for 60 seconds.  In "dictionary" mode, I grab the recommended dictionary at the end of each run and load it into the next run.  No-dictionary means it has to try to make a dictionary from scratch in each 60 second run.  There's no "don't even try to make a dictionary" option, I think.

No value profiling means just that, it doesn't do value profiling.  Note that compiling "fsanitize=fuzzer" (which everything is compiled with here) actually does the Steelix decomposition on CMP trick, already.  Value profiling is additionally doing this:  https://llvm.org/docs/LibFuzzer.html#value-profile

**Comment by agroce** [comment]
(I am investigating now, saving more info on the runs and corpus changes)

**Comment by agroce** [comment]
Very weird.

One run gets to 1775 during initialization, it looks like -- just reading the existing corpus:

```
EXTERNAL: INFO: seed corpus: files: 2441 min: 1b max: 4096b total: 768506b rss: 32Mb

EXTERNAL: #2048 pulse 
EXTERNAL:  cov: 1745
EXTERNAL:  ft: 10336
EXTERNAL:  corp: 448
EXTERNAL: /31Kb
EXTERNAL:  exec/s: 1024
EXTERNAL:  rss: 51Mb
EXTERNAL: 

EXTERNAL: #2442 INITED
EXTERNAL:  cov: 1772
EXTERNAL:  ft: 10412
EXTERNAL:  corp: 460
EXTERNAL: /42Kb
EXTERNAL:  exec/s: 1221
EXTERNAL:  rss: 55Mb
EXTERNAL: 
```

and of course maintains that level till finish:

```
EXTERNAL: #109318       DONE  
EXTERNAL:  cov: 1772
EXTERNAL:  ft: 10516
EXTERNAL:  corp: 484
EXTERNAL: /47Kb
EXTERNAL:  exec/s: 1792
EXTERNAL:  rss: 854Mb
EXTERNAL: 
```

But the next run reads in the corpus:

```
EXTERNAL: INFO: seed corpus: files: 2477 min: 1b max: 4096b total: 776092b rss: 32Mb

EXTERNAL: #2048 pulse 
EXTERNAL:  cov: 1745
EXTERNAL:  ft: 10356
EXTERNAL:  corp: 445
EXTERNAL: /31Kb
EXTERNAL:  exec/s: 1024
EXTERNAL:  rss: 51Mb
EXTERNAL: 

EXTERNAL: #2478 INITED
EXTERNAL:  cov: 1745
EXTERNAL:  ft: 10455
EXTERNAL:  corp: 458
EXTERNAL: /43Kb
EXTERNAL:  exec/s: 826
EXTERNAL:  rss: 55Mb
EXTERNAL: 
```

and has lower coverage.  Where did that coverage go?

**Comment by agroce** [comment]
I will have to try again, with the assert that detects dropped coverage, and copy the entire corpus directory after each run to see what's going on in detail.  Of course, normally you'd have many fewer restarts than thus, unless you crashed a lot or ran out of memory frequently...

**Comment by agroce** [comment]
Ok, storing the corpus and replaying from it, there is a bug somewhere.  Same corpus, if you don't use -use_value_profile=1 it always produces the (correct, I assume) coverage of 1746.  But if you run with -use-value_profile=1 AND the same seed as in the instance where there is the spike, you get coverage of 1773.  This is just running libFuzzer with =runs=|corpus| so all it does it load the corpus -- the message after INITED is DONE, at same test execution.

Since there's no mutation/generation going on here, the fact the seed matters is pretty fishy.

**Comment by agroce** [comment]
Using a memory of paths produced at least seems to not be helpful.  My guess is libFuzzer is capable of basically doing what needs doing (duplicating bytes chosen), and the time spent exploring coverage of the memory is lost fuzzing effort.  Just one program, of course, but it would certainly be nice to NOT have to worry about this kind of thing.  Ideally, as much as possible, one writes the simplest harness, and either DeepState or the back-end handles this kind of pure-efficiency-not-semantics-of-tests/spec aspect.

![memfatals](https://user-images.githubusercontent.com/967816/45589055-eedef700-b8d3-11e8-8a49-5b7275f923e7.png)

Green is testfs without memory (just make bytes for each path), red is with a memory for up to five paths that can be reused in future operations.  Y-axis is # of unique fatals detected (there are 3 known about to find).  Coverage is incomparable because the memory adds coverage targets to explore.

**Comment by agroce** [comment]
At time = 360 seconds, the confidence interval on green is 2.0 - 2.0 -- it's always found 2 of the three faults by that time.
