### ISSUE TITLE
Add mac OS X symbol support

### ISSUE THREAD

**Issue by pgoodman** [trailofbits/deepstate#12]
Symbols are mangled to be prefixed with an `_` on a mac, and so that's making DeepState unable to find things like `DeepState_Setup`. The way that deepstate goes and finds its initial symbols should be modified to also look for a `_`-prefixed variant.

**Comment by agroce** [comment]
I glanced at this again, and thinking about this error:

~/deepstate/build/examples$ deepstate OneOf
CRITICAL:deepstate.mcore:Cannot create Manticore instance on binary OneOf: Binary OneOf not supported.

could it be that it "works" but the build just creates Mac binaries for the examples, when manticore of course expects Linux ELF?

**Comment by pgoodman** [comment]
I suppose yeah, Manticore just can't handle Mach-O.

**Comment by agroce** [comment]
Ditto angr:

WARNING | 2018-02-21 22:47:53,276 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
WARNING | 2018-02-21 22:47:53,298 | cle.backends.macho | The Mach-O backend is not well-supported. Good luck!
WARNING | 2018-02-21 22:47:53,303 | cle.backends.macho.symbol | Rebasing not implemented for Mach-O
...
CRITICAL | 2018-02-21 22:47:53,389 | deepstate.angr | Execution never hit `DeepState_Setup` in binary `/Users/alex/deepstate/build/examples/IntegerArithmetic`

**Comment by agroce** [comment]
So, we maybe have a working DeepState on Mac, just no working backends (unless Dr. Fuzz is Mac-friendly, I didn't look yet).

**Comment by agroce** [comment]
Dr. Memory would likely work if we made a build option to create 32 bit binaries; the mac release doesn't support 64 bit mac binaries.

**Comment by agroce** [comment]
I think we have mac symbol support working now, we just don't have a reasonable path to using angr/manticore other than "cross-compile to ELF."  Fuzzing should work.
