### ISSUE TITLE
Post SECDEV slides

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#123]
Plus VM?

**Comment by agroce** [comment]
Peter, Gustavo, can one of you post the slides we used to the trailofbits presentation repo, and add the link in a comment -- we can then link our mention of the SECDEV tutorial to the slides

**Comment by ggrieco-tob** [comment]
https://github.com/trailofbits/publications/pull/11

**Comment by agroce** [comment]
Done!
