### ISSUE TITLE
Change to how OneOf/Ranges work in fuzzing/test execution?

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#126]
Right now, OneOf translates to DeepState_UIntInRange.  And all Ranges are handled by 1) grabbing the next few bytes and using them as the value then 2) doing an ASSUME to make sure they are in the right range.

This is ideal for symbolic execution, but in some ways it's not ideal for fuzzing.

I see fuzzing as a process of parsing a stream of bytes into a test case defined by the DeepState API.  In that context, if the fuzzer provides bytes that can be _translated_ into a valid input, then it should be fine to just do so.  Using modulo arithmetic any set of bytes for a Range can be unambiguously turned into an in-range input.  You then use the transformed (parsed) value as the actual value.  Fuzzer bytes map in a many-to-one way to execution-time bytes.

Right now, what happens is that a fuzzer has to do lots of work to "figure out" the range on a OneOf or any Range construct, with lots of tests just abandoned mid-stream due to an assumption violation due to this kind of thing.  That's inefficient.  It might make more sense to change all ranges so that:

1) In symbolic world, it works just like now

2) In any other context (including replay) it avoids the ASSUME and just translates the bytes into a valid value.

You can't use it for arbitrary in-harness ASSUME statements, of course, since you don't have a clue how to change values, and they may not be raw input bytes, but for ranges (which are a pretty common case, I guess), seems like this could improve fuzzing and is generally harmless.  It is a little ugly, in that semantics of a test case are different in symbolic world and non-symbolic world, but in a way I think it's fine; the assume is just an efficiency hack.  If we didn't have assume and symbolic tools weren't guaranteed to produce satisfying assignments, we could do the mod trick there, too.  We don't since we know that path won't be taken, and it would add a pointless bit of computation.

**Comment by pgoodman** [comment]
Here's the beginning of an idea, but not sure if it fits in yet.

Make a `DeepState_Split(N)` function, exposing it to symbolic execution via the APIs array for hooking. It would work as follows: it takes in the number of forks to generate, and internally causes that `N` state forks, and returns a concrete integer index of which of the `N` forks execution now belongs. So at this point, choices are not actually part of the input at all... (hence it being the seed of an idea). What you do with this returned value, or how it works in concrete execution/replay mode, is as-of-yet undefined.

**Comment by pgoodman** [comment]
Could be: `uint32_t DeepState_Split(uint32_t, uint32_t *)`, where it takes in `N` options and a pointer to four bytes in `DeepState_Input`, writes over those bytes in symbolic execution, or in concrete execution, reads those bytes directly, and then returns the value.

**Comment by pgoodman** [comment]
```c++
template <typename First, typename... Rest>
First OneOf(First&& v1, Args&&... rest) {
  First vals[] = {v1, rest...};
  auto index = DeepState_Split(1+sizeof...(rest), &(DeepState_Input[DeepState_InputIndex]));
  DeepState_InputIndex += 4;
  return vals[index];  // Or if it's a callable, `vals[index]()`.
}
```

**Comment by agroce** [comment]
Less ambitious quick fix would be to have this code:

```
/* Return a symbolic value in a the range `[low_inc, high_inc]`. */
#define DEEPSTATE_MAKE_SYMBOLIC_RANGE(Tname, tname) \
    DEEPSTATE_INLINE static tname DeepState_ ## Tname ## InRange( \
        tname low, tname high) { \
      tname x = DeepState_ ## Tname(); \
      (void) DeepState_Assume(low <= x && x <= high); \
      return x; \
    }
```

have a check for fuzzing, and do a modulo formula when appropriate.  Do we have a way to say "am I fuzzing" right now?  There used to be some -DLIBFUZZER stuff, but I don't see it in the core files anywhere, and it wouldn't handle AFL etc.

**Comment by agroce** [comment]
something like:

```
/* Return a symbolic value in a the range `[low_inc, high_inc]`. */
#define DEEPSTATE_MAKE_SYMBOLIC_RANGE(Tname, tname) \
    DEEPSTATE_INLINE static tname DeepState_ ## Tname ## InRange( \
        tname low, tname high) { \
      tname x = DeepState_ ## Tname(); \
#ifdef FUZZING
      if (symbolic_run) \
            (void) DeepState_Assume(low <= x && x <= high); \
      else \
             x = low + x%(high-low); \
      return x; \
    }
```

... except it needs to by dynamic, of course now I think of it.

**Comment by pgoodman** [comment]
Another funny thing we could do is have each oneof choice value represented in the input as three integers: `<magic><choice><magic>`, where we also have the first integer of every input file be that `<magic>` number, where we create it such that the magic number is not present in any of the other bytes. This opens up interesting possibilities in terms of other magic numbers.

**Comment by agroce** [comment]
Is there currently a way to tell if we are 

1) in manticore/angr/symbolic world

vs.

2) in a test replay or a libFuzzer run?  I can detect libFuzzer via a flag, since we have to do that for other things.  I can always add a flag that detects a replay/AFL run, but I don't want to add a special-case thing if there's a better mechanism already there.

**Comment by agroce** [comment]
@pag I'm not sure how we arrange to have that first bit of an input file be `<magic>` without some serious re-engineering -- right now, our interface to AFL/libFuzzer relies completely on the fact that, other than exceptions, any ol' bytes are an ok input.  For fuzzing, my short term goal is to lower the number of invalid input files; adding a `<magic>` header is going to either complicate our interface (you have to generate it somehow, and it's not going to have any meaning since the fuzzer won't make properly marked OneOf decisions anyway) or ruin libFuzzer's day.  Am I missing something?  In some sense, I think for fuzzing what we want is to maximize the set of input bytes that turn into a complete test run.  Any extra info associated with tests maybe needs to live elsewhere.  We could pre-process bytes from fuzzers, and turn them into this, by treating them as non `<magic>`ed inputs, but this certainly complicates things like using an existing corpus from deepstate...

Am I missing something that makes this not a problem?

**Comment by agroce** [comment]
Aha, figured out we do have this, but in multiple places.  You are in symbolic world if not:  in libFuzzer mode, and if HAS_FLAG is false for all the input a file/dir options.  Simple, and definitive (ok, the DrFuzz stuff I have no idea about but not sure that is even working...)

**Comment by agroce** [comment]
I'll collect some data on impact of #127 and propose merge if good on rbtree and testfs.

**Comment by agroce** [comment]
Largely handled (more empirical comparison would be nice) in #127
