### ISSUE TITLE
Make sure we work with Angora

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#196]
https://github.com/AngoraFuzzer/Angora -- it's available and seems stable-ish now, so we should check out if there are any problems, make an eclipser-like frontend if it needs more hand-holding than AFL/libFuzzer.

**Comment by agroce** [comment]
An instance of #192

**Comment by ex0dus-0x** [comment]
See https://github.com/trailofbits/deepstate/pull/216
