### ISSUE TITLE
Support for file-based path input functionality

### ISSUE THREAD

**Issue by ex0dus-0x** [trailofbits/deepstate#238]
Some libraries that perform heavy amounts of serialization and deserialization to structured types might invoke high-level wrappers that require an input path parameter. For i.e.

```c
const char *path = "/path/to/file.json";
MyJSON *j = JSONReadFromFile(path);
```

Since DeepState's currently supported input functions reads from files interally with `DeepState_InitInputFromFile`, we should support a method that only stores a path (ideally parsed from `--input_test_file` or `--input_test_files_dir`), rather than a path's contents.

This method may be called `DeepState_InputPath` (which might be able to leverage `DeepState_InitInputFromPath` in some way), which we should be able to use as so:

```c
const char *path = DeepState_InputPath();
MyJSON *j = JSONReadFromFile(path);
```
This is also interesting because it allows us to introduce simple and primitive grammar-based analysis for DeepState.

**Comment by ggrieco-tob** [comment]
This is a good idea, specially if the file can be stored in RAM.
