### ISSUE TITLE
Finish DeepState API for basic C types

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#240]
You can do "anything" with a cast or `DeepState_SymbolizeData`, but we ought to provide

- `DeepState_Long`
- `DeepState_size_t`
- `DeepState_Double`

etc.

**Comment by pgoodman** [comment]
Note: `DeepState_Size()` is already done for `size_t`.

**Comment by agroce** [comment]
This is done in PR #247 -- floats are not the ideal approach as far as distribution goes, but it works
