### ISSUE TITLE
Script for updating a (docker) install

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#261]
Building DeepState's docker takes a long time, but just doing a make after pulling latest doesn't update AFL/libfuzzer/etc.  We should add a script to reinstall all the deepstate libraries and tools after a pull.

**Comment by agroce** [comment]
(should be pretty simple, just do the things the dockerfile does, except not installing eclipser, doing apt-gets, etc.)

**Comment by enflo** [comment]
I'm working on it. Can you really specify the need, I understand that once ripped the docker image and a change is made in the code is necessary to reinstall part of the dependencies (apts, etc) not?
Have you thought about introducing docker compose, to facilitate these changes?

**Comment by agroce** [comment]
That's an idea, docker compose for the stable bits, since DeepState itself is a quick build.

**Comment by enflo** [comment]
Okay, I'm gonna try to work on it. Thanks

**Comment by GrosQuildu** [comment]
Fixed in #316 . We now use Docker's multistage feature and can update each fuzzer separately. Closing.
