### ISSUE TITLE
Allow to define custom mutators for fuzzing

### ISSUE THREAD

**Issue by neuromancer** [trailofbits/deepstate#320]
It will be nice to allow to define custom mutators per test, like this one:

https://github.com/llvm-mirror/compiler-rt/blob/master/test/fuzzer/CompressedTest.cpp

**Comment by agroce** [comment]
So in theory if you write one in your harness, it should just work, right?  Have you tried?

What I'd like is for us to provide a default custom mutator that is DeepState test structure aware, e.g. uses OneOf boundaries intelligently to swap/remove.  I played with it, but for some reason custom mutators in general didn't work, then I got distracted.

**Comment by agroce** [comment]
Closing since I think #103 covers this, but specifically
