### ISSUE TITLE
Fuzzers are slow

### ISSUE THREAD

**Issue by GrosQuildu** [trailofbits/deepstate#335]
Fuzzing deepstate tests is much slower than normally instrumented binaries.

## AFL

Control sample (fast.cpp):
```cpp
#include <cstdio>
#include <deepstate/DeepState.hpp>

int main() {
    char x[100];
    scanf("%100s", x);
    if (x[0] == 'l')
        if (x[1] == 'u')
            if (x[2] == 'l')
                if (x[3] == 'z') {
                    int *p = (int*)0xcafeeeee;
                    *(p+1) = 0xfafaafaf;
                }
    return 0;
}
```

```shell
afl-clang++ ./fast.cpp -o fast.afl
mkdir input && echo X > input/X  # same seed as deepstate's default
afl-fuzz -i input -o out_fast ./fast.afl
# check exec/s
```

Research sample (slow.cpp):
```cpp
#include <deepstate/DeepState.hpp>

TEST(a,b) {
    char *x = DeepState_CStr_C(100, 0);
    if (x[0] == 'l')
        if (x[1] == 'u')
            if (x[2] == 'l')
                if (x[3] == 'z') {
                    int *p = (int*)0xcafeeeee;
                    *(p+1) = 0xfafaafaf;
                }
}
```

```shell
deepstate-afl --compile_test ./slow.cpp --out_test_name slow
deepstate-afl -o out_slow ./slow.afl --fuzzer_out
# check exec/s
```

====================

## libFuzzer

Control sample (fast.cpp):
```cpp
#include <cinttypes>
#include <cstring>

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *x, std::size_t Size) {
    if (Size < 8)
        return 0;

    if (strcmp((char*)x, "lalakoko") == 0) {
        int *p = (int*)0xcafeeeee;
        *(p+1) = 0xfafaafaf;
    }
    return 0;
}
```

```shell
clang++ ./fast.cpp -fsanitize=fuzzer,undefined -o fast
./fast
# check exec/s
```

Research sample (slow.cpp):
```cpp
#include <cstring>
#include <deepstate/DeepState.hpp>

TEST(A, B) {
    char *x = DeepState_CStr_C(100, 0);
    ASSUME_GT(strlen(x), 7);

    if (strcmp(x, "lalakoko") == 0) {
        int *p = (int*)0xcafeeeee;
        *(p+1) = 0xfafaafaf;
    }
}
```

```shell
deepstate-libfuzzer --compile_test ./slow.cpp --out_test_name slow
./slow.libfuzzer
# or mkdir out_slow && deepstate-libfuzzer -o out_slow ./slow.libfuzzer --fuzzer_out
# check exec/s
```

====================

AFL control sample: around `4500` exec/s.
AFL research sample: around `2500` exec/s.

libFuzzer control sample: around `1720000` exec/s (yes, its more than 1.5 million).
libFuzzer research sample: around `30000` exec/s (yes, its 30 thousand).

Possible causes I may think of:
* deepstate produces files, which are temporarily saved to disk (not sure about that)
* deepstate library itself **is** instrumented, which is most probably excessive
* maybe deepstate forks in wrong moment? And fuzzers execute whole `main` function (which is produced by deepstate, is huge and is instrumented).

**Comment by agroce** [comment]
Deepstate AFL is definitely reading files, which is slower than stdin fuzzing, I guess, and that is probably it.  I suspect we can just fix that, actually, by making a custom AFL (and eclipser) mode that reads stdin, I meant to ages ago, but never noticed this huge slowdown.  Nice benchmarking!

I dunno WHAT is going on with libfuzzer, fork is turned off there.  Running a giant main is all I can think of, yeah.

**Comment by agroce** [comment]
DeepState library needs to be instrumented, I think, for various reasons...

**Comment by GrosQuildu** [comment]
Can we point deepstate/AFL to save the files in our location? Then we could make tmpfs which would store them in the RAM.

Instrumentation - don't know C/C++ codebase too much, but logically thinking - why we need that? We want to measure coverage on some library that we are testing + the test itself, not the DeepState library and not deepstate header files.

**Comment by agroce** [comment]
So, maybe we could avoid instrumenting the library before testing starts, but fuzzers need visibility into OneOf and assume, probably

**Comment by agroce** [comment]
Plus maybe some other things, like ifs/loops in the harness code

**Comment by agroce** [comment]
Maybe a lot is startup cost, and persistent would help?  But libfuzzer startup should be cheap, unless I did something stupid (always a good chance of that of course!) and looks horrible.

**Comment by agroce** [comment]
I think I fixed a lot of this in https://github.com/trailofbits/deepstate/commit/435dc1283639cf39706c39541de39747ccebd02e -- I hope, anyway, will try out more to see if this is the major issue

**Comment by agroce** [comment]
(basically, we did a lot of "zero out 8K buffer, then fill most or all of the buffer" with a secure memset that would always do all the zeroing

**Comment by agroce** [comment]
Ok, no, this is some but not all of the problem.  Still a big slowdown.

**Comment by agroce** [comment]
PR #370 has the libfuzzer difference for me down to 44K execs/sec vs. about 70K, so a major improvement.

**Comment by agroce** [comment]
still not ideal, but improving.

for libfuzzer:
fast:
exec/s: 1398101
slow:
exec/s: 131072

note these aren't exactly compatible, since DeepState always runs the test and libfuzzer drops anything with small size

**Comment by agroce** [comment]
(new ratio is 5x better)

**Comment by agroce** [comment]
afl is even closer now:

(in docker so probably hurting both)

fast:
400.2/sec

slow:
300/sec

not much slowdown, given what's going on, really.

**Comment by agroce** [comment]
other than not doing persistent mode, I think this is now basically ok
