### ISSUE TITLE
Docker doesn't build

### ISSUE THREAD

**Issue by akhikolla** [trailofbits/deepstate#343]
When I use the following command
**$ docker build -t deepstate-base -f docker/base/Dockerfile docker/base
$ docker build -t deepstate --build-arg make_j=6 -f ./docker/Dockerfile .**
to build docker it shows me an error unable to prepare context - docker/base not found
![build-fail](https://user-images.githubusercontent.com/31878891/76036513-92292f00-5f01-11ea-9d4c-91e458cd9264.PNG)

Error is because we are trying to access docker/base also I think the docker-base-layer is inaccessible. 
But when I use this command which is present in the deepstate-c-blosc2 page to build docker:
**docker build -t deepstate . -f docker/Dockerfile**
it works fine.
Can someone please help me with this.

**Comment by disconnect3d** [comment]
The `docker build -t deepstate-base -f docker/base/Dockerfile docker/base` command works for me when I am on this commit:
```
* 089587c - (HEAD -> master, origin/master, origin/HEAD) handle weird chars in candidate output (6 days ago) <agroce>
```

Are you sure you are using latest git commit of Deepstate's master branch? Can you show the output of `git status` so we can validate it?

**Comment by akhikolla** [comment]
Git status gives the following 
![gitstatus](https://user-images.githubusercontent.com/31878891/76132437-44c7c300-5fd0-11ea-8b4e-adb1b9cc4e61.PNG)

**Comment by akhikolla** [comment]
I am using the latest Deepstate master branch. Still showing the same docker/base not found

**Comment by disconnect3d** [comment]
The `git status` doesn't show the commit id of the last commit, my bad. Can you show `git rev-parse HEAD`?

**Comment by akhikolla** [comment]
It gives me something as follows:
![ver](https://user-images.githubusercontent.com/31878891/76170879-6d23fe80-6143-11ea-8be6-bfa2c2654975.PNG)
Will this do?

**Comment by GrosQuildu** [comment]
Maybe try: `docker build -t deepstate-base -f Dockerfile docker/base`

Docker `-f` is relative to the context afaik.

**Comment by disconnect3d** [comment]
Yeah, updating the repository to its latest version/master branch should do the job. Please re-open if it does not.
