### ISSUE TITLE
Random Fuzzing outputs generated with '?'

### ISSUE THREAD

**Issue by akhikolla** [trailofbits/deepstate#345]
I am running Runlen from examples in deepstate using Eclipser
(mkdir temp & deepstate-eclipser ./Runlen -o temp --timeout 30) and I get the following randomized inputs with '?' following them and it shows nodes(Left/Right)
![err1](https://user-images.githubusercontent.com/31878891/76257386-d58be200-620e-11ea-8457-2a9ec4ca1f2c.png)
![err2](https://user-images.githubusercontent.com/31878891/76257388-d6247880-620e-11ea-93a3-5c05b50098fb.png)
![err3](https://user-images.githubusercontent.com/31878891/76257389-d6247880-620e-11ea-99e1-ee1dfc31b700.png)

Can someone please explain me what does these inputs generated with '?' mean and how are they passed on to the code and how can they find crashes/other vulnerabilities in code?
How can I know which input aborts the code because I don't see any error message after code aborts or reason why it failed?

**Comment by ggrieco-tob** [comment]
Hi @akhikolla 

DeepState can work using third-party tools to get new inputs to test. In this case, DeepState is using [Eclipser](https://github.com/kukido/eclipser) and showing it's internal output. I believe it is showing the individual input bytes that the tool guessed (according to collected "linear" constrains), but perhaps you could ask their authors about clarification on the meaning of the `?`.

**Comment by agroce** [comment]
Yeah, I think it's just unprintable bytes
