### ISSUE TITLE
Ensembler Crash in Docker

### ISSUE THREAD

**Issue by Travmatth** [trailofbits/deepstate#348]
## Expected behavior
Executing `deepstate-ensembler` should start fuzzers
```
$ mkdir ensembler_seeds
$ printf "\xab\xcd" >> ensembler_seeds/initial
$ deepstate-ensembler -i ensembler_seeds/ --test examples/IntegerOverflow.cpp
``` 
## Actual behavior
`deepstate-ensembler` crashes, complaining of a missing variable:
```
user@bb2e0f74dd7a:~/deepstate$ deepstate-ensembler -i ensembler_seeds/--test examples/IntegerOverflow.cpp
INFO:deepstate:Setting log level from DEEPSTATE_LOG: 2
Traceback (most recent call last):
  File "/usr/local/bin/deepstate-ensembler", line 11, in <module>
    load_entry_point('deepstate==0.1', 'console_scripts', 'deepstate-ensembler')()
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/executors/auxiliary/ensembler.py", line 368, in main
    ensembler = Ensembler()
TypeError: __init__() missing 1 required positional argument: 'envvar'
```
## Information about the Issue
Seems to be related to https://github.com/trailofbits/deepstate/pull/263, attempted to imitate https://github.com/trailofbits/deepstate/commit/be654705d01e3e460d6683d9e82ac26dcfe9a425 by creating an `ENSEMBLER_HOME=/usr/local/bin` variable and adding it to `$PATH`, but no change in the crashing status was observed.
## Steps to reproduce the behavior
1. Download, build, launch deepstate docker container
2. Run:
```
$ mkdir ensembler_seeds
$ printf "\xab\xcd" >> ensembler_seeds/initial
$ deepstate-ensembler -i ensembler_seeds/ --test examples/IntegerOverflow.cpp
```

**Comment by GrosQuildu** [comment]
Well, after my PRs the ensembler is broken and need fixes. See #331 . First step for the fix would be to implement fuzzers synchronization and tests for that. Then the ensembler that spawns and maintain the fuzzers.

**Comment by agroce** [comment]
Closing since this is captured in #377 which is more up to date
