### ISSUE TITLE
fuzz.py swallows fuzzer return status

### ISSUE THREAD

**Issue by jscriven-digimarc** [trailofbits/deepstate#350]
fuzz.py correctly catches the exit status of a fuzzer and raises a FuzzFrontendException.  That exception is immediately caught within the same method (run) and turned in to a L.error message, and stops the fuzzer loop (fun_fuzzer = False).  The main function never processes the exception and returns 0, implying deepstate ran successfully.  

It would be helpful to propagate the exception up somehow (maybe after cleanup) so the return status of the fuzzer causes deepstate main() to return with 1 (it already catches AnalysisBackendError).

**Comment by GrosQuildu** [comment]
Good idea. We may extend `AnalysisBackendError` with `fuzzer_return_code` field and use it in the main. Interested in making PR?

**Comment by jscriven-digimarc** [comment]
PR in.  please note comment in pull req regarding control flow.  I'm open to suggestions.  We pulled this change into our fuzzing ensembler and it's working fine.

**Comment by GrosQuildu** [comment]
Closed with #351
