### ISSUE TITLE
DeepState_RandomGenerators() doesn't generate random inputs

### ISSUE THREAD

**Issue by akhikolla** [trailofbits/deepstate#353]
I tried passing the random inputs to generated from DeepState_Double() and DeepState_DoubleInRange() to an Rcpp function it displays zeros when DeepState_Double() is used and DeepState_DoubleInRange(100,1000) gives 1000
Passing random inputs to a NumericVector data_vec
``` 
Rcpp::NumericVector data_vec(n_data);
for(int i=0; i<n_data; i++){
    data_vec[i] = DeepState_DoubleInRange(100,1000);
    //data_vec[i] = DeepState_Double();
  }
  std::cout << "after assignment\n";
  for(int i=0; i<n_data; i++){
    std::cout << "i: "<< i <<" datavec: "  << data_vec[i] << "\n";
  }
```
Output when DeepState_Double() is passed:
![image](https://user-images.githubusercontent.com/31878891/78711231-7f709400-78cb-11ea-8ea3-f5619e5f7adf.png)

Output when DeepState_DoubleInRange(100,1000) is passed:
![image](https://user-images.githubusercontent.com/31878891/78711349-adee6f00-78cb-11ea-9c4d-78b672d57389.png)

The commands used to compile the code:
COMMON_FLAGS=binsegRcppTest.o -L/usr/lib/R/site-library/RInside/include/lib -Wl,-rpath=/usr/lib/R/site-library/RInside/include/lib -L${R_HOME}/lib -Wl,-rpath=${R_HOME}/lib -L/home/akhila/deepstate/src/lib -Wl,-rpath=/home/akhila/deepstate/src/lib -lR -lRInside -ldeepstate

binsegRcppTest: binsegRcppTest.o
	clang++ -o binsegRcppTest ${COMMON_FLAGS} /home/akhila/R/binsegRcpp/src/*.o
	./binsegRcppTest
binsegRcppTest.o: binsegRcppTest.cpp
	clang++ -I${R_HOME}/include -I/home/akhila/deepstate/src/include -I/usr/lib/R/site-library/Rcpp/include -I/usr/lib/R/site-library/RInside/include binsegRcppTest.cpp -o binsegRcppTest.o -c

Also when I run the Testharness passing these random inputs the code doesn't make(compile) the file(*.cpp). It shows following:
![image](https://user-images.githubusercontent.com/31878891/78711881-92379880-78cc-11ea-912d-4e22a7e3cc82.png)

Do I have to add any .a files during the compilation? Like /usr/local/lib/libdeepstate.a in the compile line

**Comment by agroce** [comment]
You aren't running a fuzzer.  If you just run the deepstate binary without any options you get a default test.  Try running the executable ./binseqRcppTest with arguments `--fuzz` and `--min_log_level 0` and you should get LOTS of different values
