### ISSUE TITLE
Request for new seed_count argument

### ISSUE THREAD

**Issue by akhikolla** [trailofbits/deepstate#362]
Hello,

I am using deepstate to test the function in my Rcpp package. When I run the testharness for an Rcpp function on the cluster I get around 300 fail/crash files, but when I run the same code on my local machine or Travis it will generate around 3-4 crash files.

The number of files that are getting generated keeps varying even though we set the timeout flag(to be same) the number of inputs that are getting generated keeps varying. Is there a way/flag to restrict the number of input seeds that are getting generated during the compile-time instead of a timeout flag? 

Thanks

**Comment by agroce** [comment]
I think this isn't really that useful compared to a timeout; # of tests is fairly meaningless, and I'm not aware of many fuzzers that support this option.
