### ISSUE TITLE
--fuzz produces the same test each time unless run with --no_fuzz

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#383]
Sort of obvious, rand() is going to reproduce without changing the generator.

One solution would just be to force no_fork when doing --fuzz though there might be some use of forking I can't think of off hand.

@pgoodman opinions?

and as we've noted before, using `rand()` is probably not really optimal, but anyway

**Comment by agroce** [comment]
Eh, just issue a complaint and fail for now, can revisit if there's a real need to forking fuzzing

**Comment by laurynas-biveinis** [comment]
I think the title means to say "--no_fork" at the end?

**Comment by agroce** [comment]
Indeed.  Though I'm curious what --fuzz --no_fuzz would do.  Explode, probably.
