### ISSUE TITLE
The Deepstate CI pipeline has been failing for 3 months due to python version issues

### ISSUE THREAD

**Issue by PenelopeFudd** [trailofbits/deepstate#391]
Hi;

Deepstate's CI badge is red: <img src="https://camo.githubusercontent.com/ac8987c83ea0de76458899bc21e14fef467c1d1e750abee271305fdf49dec91a/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f776f726b666c6f772f7374617475732f747261696c6f66626974732f6465657073746174652f43492f6d6173746572" alt="Build Status" data-canonical-src="https://img.shields.io/github/workflow/status/trailofbits/deepstate/CI/master" style="max-width: 100%;">
* https://github.com/trailofbits/deepstate/actions?page=4&query=workflow%3ACI
Here's the first failing build:
* https://github.com/trailofbits/deepstate/runs/3252004612?check_suite_focus=true
Here's the error message:
```
Downloading PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)
ERROR: Package 'manticore' requires a different Python: 3.6.14 not in '>=3.7'
Error: Process completed with exit code 1.
```

Hope it's not caused by a dependency nightmare!

Cheers

**Comment by agroce** [comment]
Thanks, may be an easy fix...

**Comment by agroce** [comment]
I'm guessing just fixing Python to be 3.7 will do it, thanks!  I've been swamped with a lot more teaching than usual, so not checking in on DeepState as much lately since no big changes have been made for a while.

**Comment by agroce** [comment]
Fixed!  Thanks again!
