### ISSUE TITLE
Investigate performance of Manticore executor

### ISSUE THREAD

**Issue by ranweiler** [trailofbits/deepstate#43]
The Manticore executor (currently the default) seems very slow compared to the angr executor, and slower than what I'd expect from Manticore generally. Is our executor implementation doing anything degenerate? If we can't do any better with Manticore as-is, are there upstream changes that would enable us to improve perf?

Compare the below (representative) runs against the `IntegerOverflow` example binary, which uses the DeepState unit test API.

Manticore executor:
```
$ time deepstate --output_test_dir=out examples/IntegerOverflow
...
real    16m33.590s
user    16m3.426s
sys     0m22.298s
```

angr executor:
```
$ time deepstate-angr --output_test_dir=out examples/IntegerOverflow
...
real    0m13.395s
user    0m13.360s
sys     0m0.246s
```

**Comment by ranweiler** [comment]
I profiled a partial Manticore-powered symbolic execution of the not-yet-merged `TakeOver` example. Results hidden below.

<details><summary>Click here to expand</summary>
<pre>
Mon Feb 19 17:36:47 2018    profile.out
         1831234739 function calls (1687811436 primitive calls) in 771.948 seconds
   Ordered by: cumulative time
   List reduced from 667 to 50 due to restriction <50>
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  771.948  771.948 <string>:1(<module>)
        1    0.000    0.000  771.948  771.948 build/bdist.linux-x86_64/egg/deepstate/main_manticore.py:373(main_takeover)
        1    0.000    0.000  771.908  771.908 /home/joe/src/manticore/manticore/manticore.py:613(run)
        1    0.000    0.000  771.897  771.897 /home/joe/src/manticore/manticore/manticore.py:382(_start_workers)
        1    0.988    0.988  771.897  771.897 /home/joe/src/manticore/manticore/core/executor.py:413(run)
  1048619    1.695    0.000  712.541    0.001 /home/joe/src/manticore/manticore/core/state.py:124(execute)
  1048619    1.907    0.000  710.223    0.001 /home/joe/src/manticore/manticore/platforms/linux.py:2117(execute)
  1048619   12.539    0.000  707.724    0.001 /home/joe/src/manticore/manticore/core/cpu/abstractcpu.py:796(execute)
 35855317   23.236    0.000  443.170    0.000 /home/joe/src/manticore/manticore/utils/event.py:115(_publish)
179275565/35855317  177.712    0.000  366.353    0.000 /home/joe/src/manticore/manticore/utils/event.py:121(_publish_impl)
  1048300    3.442    0.000  343.559    0.000 /home/joe/src/manticore/manticore/core/cpu/abstractcpu.py:917(new_method)
 10249074   10.799    0.000  325.234    0.000 /home/joe/src/manticore/manticore/core/cpu/abstractcpu.py:526(__getattr__)
 11763659   13.165    0.000  309.372    0.000 /home/joe/src/manticore/manticore/core/cpu/abstractcpu.py:512(read_register)
  5699427    6.886    0.000  142.376    0.000 /home/joe/src/manticore/manticore/core/cpu/abstractcpu.py:537(__setattr__)
  4229760    5.047    0.000  133.436    0.000 /home/joe/src/manticore/manticore/core/cpu/abstractcpu.py:499(write_register)
179275565   78.155    0.000   99.396    0.000 /usr/lib64/python2.7/weakref.py:407(items)
  1407832    2.388    0.000   79.509    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:646(read)
 15948493   25.790    0.000   69.943    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:462(__contains__)
179275566   54.846    0.000   68.137    0.000 /home/joe/src/manticore/manticore/utils/event.py:96(_get_signal_bucket)
  1048619    2.387    0.000   65.150    0.000 /home/joe/src/manticore/manticore/core/cpu/abstractcpu.py:841(_publish_instruction_as_executed)
  1048623    0.572    0.000   58.353    0.000 /home/joe/src/manticore/manticore/core/executor.py:299(is_shutdown)
  1048623    0.579    0.000   57.781    0.000 /usr/lib64/python2.7/multiprocessing/managers.py:1008(is_set)
   286295    0.250    0.000   57.673    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:2508(MOV)
  1048684    1.643    0.000   57.207    0.000 /usr/lib64/python2.7/multiprocessing/managers.py:746(_callmethod)
 35855317   37.679    0.000   53.580    0.000 /home/joe/src/manticore/manticore/utils/event.py:101(_check_event)
   146025    0.114    0.000   52.432    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:1192(ADD)
   146025    1.392    0.000   52.318    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:1213(_ADD)
  1048686   49.428    0.000   49.428    0.000 {method 'recv' of '_multiprocessing.Connection' objects}
   685329    1.563    0.000   46.289    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:662(write)
 15948493   33.991    0.000   44.152    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:453(all_registers)
   319431    2.046    0.000   32.428    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:620(address)
  4229760    9.411    0.000   26.198    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:550(write)
   257009    1.049    0.000   24.512    0.000 /home/joe/src/manticore/manticore/core/cpu/abstractcpu.py:577(read_int)
    85925    0.421    0.000   22.872    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:891(TEST)
    39601    0.024    0.000   22.835    0.001 /home/joe/src/manticore/manticore/core/cpu/x86.py:3757(SHL)
    66247    0.181    0.000   20.487    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:1242(CMP)
    39601    0.803    0.000   19.831    0.001 /home/joe/src/manticore/manticore/core/cpu/x86.py:3720(SAL)
  3374178    5.404    0.000   18.670    0.000 /home/joe/src/manticore/manticore/core/cpu/abstractcpu.py:127(_reg_name)
   104299    0.706    0.000   17.680    0.000 /home/joe/src/manticore/manticore/core/cpu/abstractcpu.py:556(write_int)
    79482    0.480    0.000   17.347    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:775(_calculate_CMP_flags)
  2278026    4.558    0.000   15.665    0.000 /home/joe/src/manticore/manticore/core/memory.py:747(access_ok)
   350264    1.216    0.000   15.425    0.000 /home/joe/src/manticore/manticore/core/memory.py:915(read)
 11763659    8.711    0.000   14.380    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:579(read)
    60507    0.102    0.000   14.140    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:5171(MOVZX)
181757477   13.482    0.000   13.482    0.000 {method 'setdefault' of 'dict' objects}
107565985   13.395    0.000   13.395    0.000 {method 'startswith' of 'str' objects}
179275565   13.281    0.000   13.281    0.000 {method 'items' of 'dict' objects}
   104299    0.974    0.000   12.945    0.000 /home/joe/src/manticore/manticore/core/memory.py:990(write)
    65710    0.038    0.000   12.243    0.000 /home/joe/src/manticore/manticore/core/cpu/x86.py:3404(JNZ)
179275608   12.240    0.000   12.240    0.000 {method 'iteritems' of 'dict' objects}
</pre>
</details>

**Comment by disconnect3d** [comment]
Hey,

There is plenty of things that can be done to improve manticore speed. See how easy can it be in some cases: https://github.com/trailofbits/manticore/pull/755

Generally we have some classes that are used heavily and we might need to redesign them a bit.

Some of my ideas:
* remove properties - yeah, we use them to make things "read only" which is cool, but maybe it is not the best way for attributes that are heavily used (maybe registers?)
* use [`__slots__` magic](http://book.pythontips.com/en/latest/__slots__magic.html) - this may require redesigning few things, but it might give us a lot in terms of memory and speed
* cythonize crucial code with Cython - which is a way to use C constructs inside Python. Cython compiles the code to C but you are still stuck to `Python_Object*` (or whatever the Python object wrapper is called in C) in some cases. Anyway, this still should speed up things as you get native, optimized code.

Another way would be to try using manticore with [pypy](https://pypy.org/) - this is a JIT-ed Python version and it might speed things a lot. The question to ask here is: does Manticore work with PyPy?
Anyway, this should speed up angr as well.

---

Anyway, the result of this issue should be an issue on manticore project I guess ;p.

**Comment by pgoodman** [comment]
Some performance improvements I made to franken-pysymemu (pysymemu became manticore) for the CGC included:

 - Using `__slots__` everywhere
 - Defining `__setstate__` and `__getstate__` with the most trivial data structure usage (all `tuple`s).
 - Making is so that serializing (via `pickle`) forked states was effectively O(1) cost in the N-solution case solutions. Did this by saving the pre-fork, serialized state to disk, and making N-1 hard links to that file (for a total of N 'copies' of the original file for each of N forks), and then storing a state transition function in memory, so when you revive a state, you then apply the transition function to the unserialized state (e.g. concretize register EAX to value `10`).
 - Removing all temporary fixed list creations (especially in `assert`s), and replacing them with uses of global tuples
 - Complete re-implementation of memory (probably not appropriate to port)
 - Make it so that memory loads/stores never construct temporary list objects, and instead just re-use pre-defined list objects (one for each of 1-, 2-, 4-, 8-, 16-byte loads).
 - Rewrite almost all functional `any`, `all`, `map`, etc. uses in terms of simple `for` loops.
 - Completely different system for event monitoring.

**Comment by mossberg** [comment]
Very little effort has been put into optimizing Manticore (we've mostly been focused on functionality), and there's definitely lots of low hanging optimization fruit available!

Also, there are _many_ assert statements in Manticore, that I suspect impose a significant performance hit.

**Comment by ranweiler** [comment]
Okay, good to know! So it sounds like this is really a Manticore issue, not the DeepState executor accidentally using the Manticore API in a perf-degenerate way, which was my concern.

@mossberg, is there an appropriate Manticore issue that we can link to this one to capture the above strategies, or should we open a new one?

**Comment by mossberg** [comment]
There is not; and yes, I would very much appreciate it if you created a new issue for tracking optimizations :)

**Comment by ranweiler** [comment]
I opened a tracking issue for Manticore perf, and am closing this out, since we don't seem to be up to anything dubious in DeepState proper.
