### ISSUE TITLE
Bounties?

### ISSUE THREAD

**Issue by bostick** [trailofbits/deepstate#433]
The Contributing section of the README says:
> All accepted PRs are awarded bounties by Trail of Bits. Join the #deepstate channel on the [Empire Hacking Slack](https://slack.empirehacking.nyc/) to discuss ongoing development and claim bounties. Check the [good first issue](https://github.com/trailofbits/deepstate/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) label for suggested contributions.

I joined the #deepstate channel and asked how bounties work, but I didn't receive a reply.

Is there any information about how bounties work? Sorry if this info is already described somewhere else.

**Comment by agroce** [comment]
@pgoodman anyone?  Is this still the case?

**Comment by pgoodman** [comment]
Answered on Slack.
