### ISSUE TITLE
Repo title

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#57]
Probably just a quibble, but the "DeepState augments C/C++ Test-Driven Development with Symbolic Execution" title might turn off people who do unit testing but don't think of it as TDD, and hides the fact it also allows fuzzing (the first seems a bigger deal than the latter).

**Comment by ranweiler** [comment]
@agroce how about something like: "A unit test-like interface for fuzzing and symbolic execution"?

**Comment by agroce** [comment]
That sounds good to me.

**Comment by ranweiler** [comment]
Cool! Looks like I don't have permissions to edit the title, but cc @pgoodman?

**Comment by dguido** [comment]
done
