### ISSUE TITLE
Make useful travis tests

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#64]
Should at minimum:

- run angr and manticore (in individual tasks) on at least one example

- check for output matching a template for failing/passing properties

Ideally run in a fuzzer, but we may need assumptions fixed for that.

**Comment by agroce** [comment]
As of dcb1ce6518d897d367c4783eb621618513e4e8c3 we have some basic smoke tests that pass, and pyflakes checking for trivial bugs in the Python (we had some prior to this).

**Comment by agroce** [comment]
Now have checks on Primes, OneOf, and IntegerArithmetic examples (last using multiple workers).  All pass for angr, but manticore fails for Primes and OneOf with similar symptoms.

**Comment by ggrieco-tob** [comment]
Let's create a bug report for the manticore issue. Also, it could be a good idea to show the state of the build status using a label:

[![Build Status](https://travis-ci.org/trailofbits/deepstate.svg?branch=master)](https://travis-ci.org/trailofbits/deepstate)

**Comment by agroce** [comment]
Done and done.

**Comment by agroce** [comment]
As of #68 all examples that won't timeout the 50 minute Travis limit are included and checked.

**Comment by agroce** [comment]
(and with #70 all should now pass)

Missing checks for file system presence of the generated tests; in long run we really want a round-trip test:  we have a replay facility (which might work via the mechanisms for file-based fuzzing suggested in #7) and check that each failing test replays with a failure, and each passing test replays without failure.  That's what I do in TSTL tests, since checking the exact bytes for most of these examples is not robust to solver/back-end changes.

**Comment by agroce** [comment]
I think now #68 accomplishes this.  We can close this once someone reviews.
