### ISSUE TITLE
Make ready for Python 3 switchover

### ISSUE THREAD

**Issue by agroce** [trailofbits/deepstate#91]
angr is soon going to also be migrating:  https://github.com/angr/angr/issues/638#issuecomment-407902752

This is probably the proper resolution for issue #85

**Comment by agroce** [comment]
("This" being -- make deepstate's python code all legitimate python 3, in prep to switch the installs for angr and manticore over to python 3)

**Comment by agroce** [comment]
Update:  angr is now Python 3, too!

https://github.com/angr/angr

**Comment by ltfish** [comment]
:) Finally!

**Comment by ggrieco-tob** [comment]
Python3 support seems to be working.
